apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-app
  namespace: {{ .Values.namespaces }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      imagePullSecrets:
        - name: {{ .Values.weatherApp.image.pullSecret }}
      containers:
        - name: weather
          image: "{{ .Values.weatherApp.image.repository }}:{{ .Values.weatherApp.image.tag }}"
          imagePullPolicy: {{ .Values.weatherApp.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.weatherApp.port }}

