apiVersion: v1
kind: Service
metadata:
  name: weather-app-svc
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: weather
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  type: {{ .Values.service.type }}

