replicaCount: 1


namespace: prod

weatherApp:
  image:
    repository: docker_user/weather_app
    tag: v17
    pullPolicy: IfNotPresent
    pullSecret: my-registry-secret
  port: 5000
  env:
    apiKeyName: weather-api-secret



service:
  type: ClusterIP
  port: 80
  targetPort: 5000
