replicaCount: 1

namespace: staging

weatherApp:
  image:
    repository: infinityam1/first_repo
    tag: v17
    pullPolicy: IfNotPresent
    pullSecret: my-registry-secret
  port: 5000





service:
  type: ClusterIP
  port: 80
  targetPort: 5000
