apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: weather-app
  namespace: {{ .Values.namespaces }}
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: weather
  template:
    metadata:
      labels:
        app: weather
    spec:
      imagePullSecrets:
        - name: {{ .Values.weatherApp.image.pullSecret }}
      containers:
        - name: weather
          image: "{{ .Values.weatherApp.image.repository }}:{{ .Values.weatherApp.image.tag }}"
          imagePullPolicy: {{ .Values.weatherApp.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.weatherApp.port }}
          env:
            - name: WEATHER_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.weatherApp.env.apiKeyName }}
                  key: WEATHER_API_KEY
  strategy:
    canary:
      steps:
        - setWeight: 20
        - pause: {duration: 30s}
        - setWeight: 50
        - pause: {duration: 30s}
        - setWeight: 100

