apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: weather-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://gitlab.com/weather-registry/weather-app-gitops
    targetRevision: main
	path: weather-app
    helm:
      valueFiles:
       - prod-values.yaml
  destination:
    server: https://<PROD-EKS-API-SERVER>   # <-- Replace with staging cluster API server URL or cluster name
    namespace: prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

